use SmartMarket
go

-- Insert LOCALIZACAO
EXEC InsertLocalizacao @concelho = 'Águeda';
EXEC InsertLocalizacao @concelho = 'Aguiar da Beira';
EXEC InsertLocalizacao @concelho = 'Albergaria-a-Velha';
EXEC InsertLocalizacao @concelho = 'Albufeira';
EXEC InsertLocalizacao @concelho = 'Alcácer do Sal';
EXEC InsertLocalizacao @concelho = 'Alcanena';
EXEC InsertLocalizacao @concelho = 'Alcobaça';
EXEC InsertLocalizacao @concelho = 'Alcochete';
EXEC InsertLocalizacao @concelho = 'Alcoutim';
EXEC InsertLocalizacao @concelho = 'Alenquer';
EXEC InsertLocalizacao @concelho = 'Alfândega da Fé';
EXEC InsertLocalizacao @concelho = 'Alijó';
EXEC InsertLocalizacao @concelho = 'Aljezur';
EXEC InsertLocalizacao @concelho = 'Aljustrel';
EXEC InsertLocalizacao @concelho = 'Almada';
EXEC InsertLocalizacao @concelho = 'Almeida';
EXEC InsertLocalizacao @concelho = 'Almeirim';
EXEC InsertLocalizacao @concelho = 'Almodôvar';
EXEC InsertLocalizacao @concelho = 'Alpiarça';
EXEC InsertLocalizacao @concelho = 'Alter do Chão';
EXEC InsertLocalizacao @concelho = 'Alvaiázere';
EXEC InsertLocalizacao @concelho = 'Alvito';
EXEC InsertLocalizacao @concelho = 'Amadora';
EXEC InsertLocalizacao @concelho = 'Amarante';
EXEC InsertLocalizacao @concelho = 'Amares';
EXEC InsertLocalizacao @concelho = 'Anadia';
EXEC InsertLocalizacao @concelho = 'Angra do Heroísmo';
EXEC InsertLocalizacao @concelho = 'Ansião';
EXEC InsertLocalizacao @concelho = 'Arcos de Valdevez';
EXEC InsertLocalizacao @concelho = 'Arganil';
EXEC InsertLocalizacao @concelho = 'Arouca';
EXEC InsertLocalizacao @concelho = 'Arraiolos';
EXEC InsertLocalizacao @concelho = 'Arronches';
EXEC InsertLocalizacao @concelho = 'Arruda dos Vinhos';
EXEC InsertLocalizacao @concelho = 'Aveiro';
EXEC InsertLocalizacao @concelho = 'Avis';
EXEC InsertLocalizacao @concelho = 'Azambuja';
EXEC InsertLocalizacao @concelho = 'Baião';
EXEC InsertLocalizacao @concelho = 'Barcelos';
EXEC InsertLocalizacao @concelho = 'Barrancos';
EXEC InsertLocalizacao @concelho = 'Barreiro';
EXEC InsertLocalizacao @concelho = 'Batalha';
EXEC InsertLocalizacao @concelho = 'Beja';
EXEC InsertLocalizacao @concelho = 'Belmonte';
EXEC InsertLocalizacao @concelho = 'Benavente';
EXEC InsertLocalizacao @concelho = 'Bombarral';
EXEC InsertLocalizacao @concelho = 'Borba';
EXEC InsertLocalizacao @concelho = 'Boticas';
EXEC InsertLocalizacao @concelho = 'Braga';
EXEC InsertLocalizacao @concelho = 'Bragança';
EXEC InsertLocalizacao @concelho = 'Cabeceiras de Basto';
EXEC InsertLocalizacao @concelho = 'Cadaval';
EXEC InsertLocalizacao @concelho = 'Caldas da Rainha';
EXEC InsertLocalizacao @concelho = 'Calheta';
EXEC InsertLocalizacao @concelho = 'Câmara de Lobos';
EXEC InsertLocalizacao @concelho = 'Caminha';
EXEC InsertLocalizacao @concelho = 'Campo Maior';
EXEC InsertLocalizacao @concelho = 'Cantanhede';
EXEC InsertLocalizacao @concelho = 'Carrazeda de Ansiães';
EXEC InsertLocalizacao @concelho = 'Carregal do Sal';
EXEC InsertLocalizacao @concelho = 'Cartaxo';
EXEC InsertLocalizacao @concelho = 'Cascais';
EXEC InsertLocalizacao @concelho = 'Castanheira de Pera';
EXEC InsertLocalizacao @concelho = 'Castelo Branco';
EXEC InsertLocalizacao @concelho = 'Castelo de Paiva';
EXEC InsertLocalizacao @concelho = 'Castelo de Vide';
EXEC InsertLocalizacao @concelho = 'Castro Daire';
EXEC InsertLocalizacao @concelho = 'Castro Marim';
EXEC InsertLocalizacao @concelho = 'Castro Verde';
EXEC InsertLocalizacao @concelho = 'Celorico da Beira';
EXEC InsertLocalizacao @concelho = 'Celorico de Basto';
EXEC InsertLocalizacao @concelho = 'Chamusca';
EXEC InsertLocalizacao @concelho = 'Chaves';
EXEC InsertLocalizacao @concelho = 'Cinfães';
EXEC InsertLocalizacao @concelho = 'Coimbra';
EXEC InsertLocalizacao @concelho = 'Condeixa-a-Nova';
EXEC InsertLocalizacao @concelho = 'Constância';
EXEC InsertLocalizacao @concelho = 'Coruche';
EXEC InsertLocalizacao @concelho = 'Corvo';
EXEC InsertLocalizacao @concelho = 'Covilhã';
EXEC InsertLocalizacao @concelho = 'Crato';
EXEC InsertLocalizacao @concelho = 'Cuba';
EXEC InsertLocalizacao @concelho = 'Elvas';
EXEC InsertLocalizacao @concelho = 'Entroncamento';
EXEC InsertLocalizacao @concelho = 'Espinho';
EXEC InsertLocalizacao @concelho = 'Esposende';
EXEC InsertLocalizacao @concelho = 'Estarreja';
EXEC InsertLocalizacao @concelho = 'Estremoz';
EXEC InsertLocalizacao @concelho = 'Évora';
EXEC InsertLocalizacao @concelho = 'Fafe';
EXEC InsertLocalizacao @concelho = 'Faro';
EXEC InsertLocalizacao @concelho = 'Felgueiras';
EXEC InsertLocalizacao @concelho = 'Ferreira do Alentejo';
EXEC InsertLocalizacao @concelho = 'Ferreira do Zêzere';
EXEC InsertLocalizacao @concelho = 'Figueira da Foz';
EXEC InsertLocalizacao @concelho = 'Figueira de Castelo Rodrigo';
EXEC InsertLocalizacao @concelho = 'Figueiró dos Vinhos';
EXEC InsertLocalizacao @concelho = 'Fornos de Algodres';
EXEC InsertLocalizacao @concelho = 'Freixo de Espada à Cinta';
EXEC InsertLocalizacao @concelho = 'Fronteira';
EXEC InsertLocalizacao @concelho = 'Funchal';
EXEC InsertLocalizacao @concelho = 'Fundão';
EXEC InsertLocalizacao @concelho = 'Gavião';
EXEC InsertLocalizacao @concelho = 'Góis';
EXEC InsertLocalizacao @concelho = 'Golegã';
EXEC InsertLocalizacao @concelho = 'Gondomar';
EXEC InsertLocalizacao @concelho = 'Gouveia';
EXEC InsertLocalizacao @concelho = 'Grândola';
EXEC InsertLocalizacao @concelho = 'Guarda';
EXEC InsertLocalizacao @concelho = 'Guimarães';
EXEC InsertLocalizacao @concelho = 'Horta';
EXEC InsertLocalizacao @concelho = 'Idanha-a-Nova';
EXEC InsertLocalizacao @concelho = 'Ílhavo';
EXEC InsertLocalizacao @concelho = 'Lagoa';
EXEC InsertLocalizacao @concelho = 'Lagos';
EXEC InsertLocalizacao @concelho = 'Lajes das Flores';
EXEC InsertLocalizacao @concelho = 'Lajes do Pico';
EXEC InsertLocalizacao @concelho = 'Lamego';
EXEC InsertLocalizacao @concelho = 'Leiria';
EXEC InsertLocalizacao @concelho = 'Lisboa';
EXEC InsertLocalizacao @concelho = 'Loulé';
EXEC InsertLocalizacao @concelho = 'Loures';
EXEC InsertLocalizacao @concelho = 'Lourinhã';
EXEC InsertLocalizacao @concelho = 'Lousã';
EXEC InsertLocalizacao @concelho = 'Lousada';
EXEC InsertLocalizacao @concelho = 'Mação';
EXEC InsertLocalizacao @concelho = 'Macedo de Cavaleiros';
EXEC InsertLocalizacao @concelho = 'Madalena';
EXEC InsertLocalizacao @concelho = 'Mafra';
EXEC InsertLocalizacao @concelho = 'Maia';
EXEC InsertLocalizacao @concelho = 'Mangualde';
EXEC InsertLocalizacao @concelho = 'Manteigas';
EXEC InsertLocalizacao @concelho = 'Marco de Canaveses';
EXEC InsertLocalizacao @concelho = 'Marinha Grande';
EXEC InsertLocalizacao @concelho = 'Marvão';
EXEC InsertLocalizacao @concelho = 'Matosinhos';
EXEC InsertLocalizacao @concelho = 'Mealhada';
EXEC InsertLocalizacao @concelho = 'Meda';
EXEC InsertLocalizacao @concelho = 'Melgaço';
EXEC InsertLocalizacao @concelho = 'Mértola';
EXEC InsertLocalizacao @concelho = 'Mesão Frio';
EXEC InsertLocalizacao @concelho = 'Mira';
EXEC InsertLocalizacao @concelho = 'Miranda do Corvo';
EXEC InsertLocalizacao @concelho = 'Miranda do Douro';
EXEC InsertLocalizacao @concelho = 'Mirandela';
EXEC InsertLocalizacao @concelho = 'Mogadouro';
EXEC InsertLocalizacao @concelho = 'Moimenta da Beira';
EXEC InsertLocalizacao @concelho = 'Moita';
EXEC InsertLocalizacao @concelho = 'Monção';
EXEC InsertLocalizacao @concelho = 'Monchique';
EXEC InsertLocalizacao @concelho = 'Mondim de Basto';
EXEC InsertLocalizacao @concelho = 'Monforte';
EXEC InsertLocalizacao @concelho = 'Montalegre';
EXEC InsertLocalizacao @concelho = 'Montemor-o-Novo';
EXEC InsertLocalizacao @concelho = 'Montemor-o-Velho';
EXEC InsertLocalizacao @concelho = 'Montijo';
EXEC InsertLocalizacao @concelho = 'Mora';
EXEC InsertLocalizacao @concelho = 'Mortágua';
EXEC InsertLocalizacao @concelho = 'Moura';
EXEC InsertLocalizacao @concelho = 'Mourão';
EXEC InsertLocalizacao @concelho = 'Murça';
EXEC InsertLocalizacao @concelho = 'Murtosa';
EXEC InsertLocalizacao @concelho = 'Nazaré';
EXEC InsertLocalizacao @concelho = 'Nelas';
EXEC InsertLocalizacao @concelho = 'Nisa';
EXEC InsertLocalizacao @concelho = 'Nordeste';
EXEC InsertLocalizacao @concelho = 'Óbidos';
EXEC InsertLocalizacao @concelho = 'Odemira';
EXEC InsertLocalizacao @concelho = 'Odivelas';
EXEC InsertLocalizacao @concelho = 'Oeiras';
EXEC InsertLocalizacao @concelho = 'Oleiros';
EXEC InsertLocalizacao @concelho = 'Olhão';
EXEC InsertLocalizacao @concelho = 'Oliveira de Azeméis';
EXEC InsertLocalizacao @concelho = 'Oliveira de Frades';
EXEC InsertLocalizacao @concelho = 'Oliveira do Bairro';
EXEC InsertLocalizacao @concelho = 'Oliveira do Hospital';
EXEC InsertLocalizacao @concelho = 'Ourém';
EXEC InsertLocalizacao @concelho = 'Ouriense';
EXEC InsertLocalizacao @concelho = 'Ourique';
EXEC InsertLocalizacao @concelho = 'Ovar';
EXEC InsertLocalizacao @concelho = 'Paços de Ferreira';
EXEC InsertLocalizacao @concelho = 'Palmela';
EXEC InsertLocalizacao @concelho = 'Pampilhosa da Serra';
EXEC InsertLocalizacao @concelho = 'Paredes';
EXEC InsertLocalizacao @concelho = 'Paredes de Coura';
EXEC InsertLocalizacao @concelho = 'Pedrógão Grande';
EXEC InsertLocalizacao @concelho = 'Penacova';
EXEC InsertLocalizacao @concelho = 'Penafiel';
EXEC InsertLocalizacao @concelho = 'Penalva do Castelo';
EXEC InsertLocalizacao @concelho = 'Penamacor';
EXEC InsertLocalizacao @concelho = 'Penedono';
EXEC InsertLocalizacao @concelho = 'Penela';
EXEC InsertLocalizacao @concelho = 'Peniche';
EXEC InsertLocalizacao @concelho = 'Peso da Régua';
EXEC InsertLocalizacao @concelho = 'Pinhel';
EXEC InsertLocalizacao @concelho = 'Pombal';
EXEC InsertLocalizacao @concelho = 'Ponta Delgada';
EXEC InsertLocalizacao @concelho = 'Ponta do Sol';
EXEC InsertLocalizacao @concelho = 'Ponte da Barca';
EXEC InsertLocalizacao @concelho = 'Ponte de Lima';
EXEC InsertLocalizacao @concelho = 'Ponte de Sor';
EXEC InsertLocalizacao @concelho = 'Portalegre';
EXEC InsertLocalizacao @concelho = 'Portel';
EXEC InsertLocalizacao @concelho = 'Portimão';
EXEC InsertLocalizacao @concelho = 'Porto';
EXEC InsertLocalizacao @concelho = 'Porto de Mós';
EXEC InsertLocalizacao @concelho = 'Porto Moniz';
EXEC InsertLocalizacao @concelho = 'Porto Santo';
EXEC InsertLocalizacao @concelho = 'Póvoa de Lanhoso';
EXEC InsertLocalizacao @concelho = 'Póvoa de Varzim';
EXEC InsertLocalizacao @concelho = 'Povoação';
EXEC InsertLocalizacao @concelho = 'Praia da Vitória';
EXEC InsertLocalizacao @concelho = 'Proença-a-Nova';
EXEC InsertLocalizacao @concelho = 'Redondo';
EXEC InsertLocalizacao @concelho = 'Reguengos de Monsaraz';
EXEC InsertLocalizacao @concelho = 'Resende';
EXEC InsertLocalizacao @concelho = 'Ribeira Brava';
EXEC InsertLocalizacao @concelho = 'Ribeira de Pena';
EXEC InsertLocalizacao @concelho = 'Ribeira Grande';
EXEC InsertLocalizacao @concelho = 'Rio Maior';
EXEC InsertLocalizacao @concelho = 'Sabrosa';
EXEC InsertLocalizacao @concelho = 'Sabugal';
EXEC InsertLocalizacao @concelho = 'Salvaterra de Magos';
EXEC InsertLocalizacao @concelho = 'Santa Comba Dão';
EXEC InsertLocalizacao @concelho = 'Santa Cruz';
EXEC InsertLocalizacao @concelho = 'Santa Cruz da Graciosa';
EXEC InsertLocalizacao @concelho = 'Santa Cruz das Flores';
EXEC InsertLocalizacao @concelho = 'Santa Maria da Feira';
EXEC InsertLocalizacao @concelho = 'Santa Marta de Penaguião';
EXEC InsertLocalizacao @concelho = 'Santana';
EXEC InsertLocalizacao @concelho = 'Santarém';
EXEC InsertLocalizacao @concelho = 'Santiago do Cacém';
EXEC InsertLocalizacao @concelho = 'Santo Tirso';
EXEC InsertLocalizacao @concelho = 'São Brás de Alportel';
EXEC InsertLocalizacao @concelho = 'São João da Madeira';
EXEC InsertLocalizacao @concelho = 'São João da Pesqueira';
EXEC InsertLocalizacao @concelho = 'São Pedro do Sul';
EXEC InsertLocalizacao @concelho = 'São Roque do Pico';
EXEC InsertLocalizacao @concelho = 'São Vicente';
EXEC InsertLocalizacao @concelho = 'Sardoal';
EXEC InsertLocalizacao @concelho = 'Sátão';
EXEC InsertLocalizacao @concelho = 'Seia';
EXEC InsertLocalizacao @concelho = 'Seixal';
EXEC InsertLocalizacao @concelho = 'Sernancelhe';
EXEC InsertLocalizacao @concelho = 'Serpa';
EXEC InsertLocalizacao @concelho = 'Sertã';
EXEC InsertLocalizacao @concelho = 'Sesimbra';
EXEC InsertLocalizacao @concelho = 'Setúbal';
EXEC InsertLocalizacao @concelho = 'Sever do Vouga';
EXEC InsertLocalizacao @concelho = 'Silves';
EXEC InsertLocalizacao @concelho = 'Sines';
EXEC InsertLocalizacao @concelho = 'Sintra';
EXEC InsertLocalizacao @concelho = 'Sobral de Monte Agraço';
EXEC InsertLocalizacao @concelho = 'Soure';
EXEC InsertLocalizacao @concelho = 'Sousel';
EXEC InsertLocalizacao @concelho = 'Tábua';
EXEC InsertLocalizacao @concelho = 'Tabuaço';
EXEC InsertLocalizacao @concelho = 'Tarouca';
EXEC InsertLocalizacao @concelho = 'Tavira';
EXEC InsertLocalizacao @concelho = 'Terras de Bouro';
EXEC InsertLocalizacao @concelho = 'Tomar';
EXEC InsertLocalizacao @concelho = 'Tondela';
EXEC InsertLocalizacao @concelho = 'Torre de Moncorvo';
EXEC InsertLocalizacao @concelho = 'Torres Novas';
EXEC InsertLocalizacao @concelho = 'Torres Vedras';
EXEC InsertLocalizacao @concelho = 'Trancoso';
EXEC InsertLocalizacao @concelho = 'Trofa';
EXEC InsertLocalizacao @concelho = 'Vagos';
EXEC InsertLocalizacao @concelho = 'Vale de Cambra';
EXEC InsertLocalizacao @concelho = 'Valença';
EXEC InsertLocalizacao @concelho = 'Valongo';
EXEC InsertLocalizacao @concelho = 'Valpaços';
EXEC InsertLocalizacao @concelho = 'Velas';
EXEC InsertLocalizacao @concelho = 'Vendas Novas';
EXEC InsertLocalizacao @concelho = 'Viana do Alentejo';
EXEC InsertLocalizacao @concelho = 'Viana do Castelo';
EXEC InsertLocalizacao @concelho = 'Vidigueira';
EXEC InsertLocalizacao @concelho = 'Vieira do Minho';
EXEC InsertLocalizacao @concelho = 'Vila de Rei';
EXEC InsertLocalizacao @concelho = 'Vila do Bispo';
EXEC InsertLocalizacao @concelho = 'Vila do Conde';
EXEC InsertLocalizacao @concelho = 'Vila do Porto';
EXEC InsertLocalizacao @concelho = 'Vila Flor';
EXEC InsertLocalizacao @concelho = 'Vila Franca de Xira';
EXEC InsertLocalizacao @concelho = 'Vila Franca do Campo';
EXEC InsertLocalizacao @concelho = 'Vila Nova da Barquinha';
EXEC InsertLocalizacao @concelho = 'Vila Nova de Cerveira';
EXEC InsertLocalizacao @concelho = 'Vila Nova de Famalicão';
EXEC InsertLocalizacao @concelho = 'Vila Nova de Foz Côa';
EXEC InsertLocalizacao @concelho = 'Vila Nova de Gaia';
EXEC InsertLocalizacao @concelho = 'Vila Nova de Paiva';
EXEC InsertLocalizacao @concelho = 'Vila Nova de Poiares';
EXEC InsertLocalizacao @concelho = 'Vila Pouca de Aguiar';
EXEC InsertLocalizacao @concelho = 'Vila Real';
EXEC InsertLocalizacao @concelho = 'Vila Real de Santo António';
EXEC InsertLocalizacao @concelho = 'Vila Velha de Ródão';
EXEC InsertLocalizacao @concelho = 'Vila Verde';
EXEC InsertLocalizacao @concelho = 'Vila Viçosa';
EXEC InsertLocalizacao @concelho = 'Vimioso';
EXEC InsertLocalizacao @concelho = 'Vinhais';
EXEC InsertLocalizacao @concelho = 'Viseu';
EXEC InsertLocalizacao @concelho = 'Vizela';
EXEC InsertLocalizacao @concelho = 'Vouzela';
EXEC InsertLocalizacao @concelho = 'Tarouca';
EXEC InsertLocalizacao @concelho = 'Tavira';
EXEC InsertLocalizacao @concelho = 'Terras de Bouro';
EXEC InsertLocalizacao @concelho = 'Tomar';
EXEC InsertLocalizacao @concelho = 'Tondela';
EXEC InsertLocalizacao @concelho = 'Torre de Moncorvo';
EXEC InsertLocalizacao @concelho = 'Torres Novas';
EXEC InsertLocalizacao @concelho = 'Torres Vedras';
EXEC InsertLocalizacao @concelho = 'Trancoso';
EXEC InsertLocalizacao @concelho = 'Trofa';
EXEC InsertLocalizacao @concelho = 'Vagos';
EXEC InsertLocalizacao @concelho = 'Vale de Cambra';
EXEC InsertLocalizacao @concelho = 'Valença';
EXEC InsertLocalizacao @concelho = 'Valongo';
EXEC InsertLocalizacao @concelho = 'Valpaços';
EXEC InsertLocalizacao @concelho = 'Velas';
EXEC InsertLocalizacao @concelho = 'Vendas Novas';
EXEC InsertLocalizacao @concelho = 'Viana do Alentejo';
EXEC InsertLocalizacao @concelho = 'Viana do Castelo';
EXEC InsertLocalizacao @concelho = 'Vidigueira';
EXEC InsertLocalizacao @concelho = 'Vieira do Minho';
EXEC InsertLocalizacao @concelho = 'Vila de Rei';
EXEC InsertLocalizacao @concelho = 'Vila do Bispo';
EXEC InsertLocalizacao @concelho = 'Vila do Conde';
EXEC InsertLocalizacao @concelho = 'Vila do Porto';
EXEC InsertLocalizacao @concelho = 'Vila Flor';
EXEC InsertLocalizacao @concelho = 'Vila Franca de Xira';
EXEC InsertLocalizacao @concelho = 'Vila Franca do Campo';
EXEC InsertLocalizacao @concelho = 'Vila Nova da Barquinha';
EXEC InsertLocalizacao @concelho = 'Vila Nova de Cerveira';
EXEC InsertLocalizacao @concelho = 'Vila Nova de Famalicão';
EXEC InsertLocalizacao @concelho = 'Vila Nova de Foz Côa';
EXEC InsertLocalizacao @concelho = 'Vila Nova de Gaia';
EXEC InsertLocalizacao @concelho = 'Vila Nova de Paiva';
EXEC InsertLocalizacao @concelho = 'Vila Nova de Poiares';
EXEC InsertLocalizacao @concelho = 'Vila Pouca de Aguiar';
EXEC InsertLocalizacao @concelho = 'Vila Real';
EXEC InsertLocalizacao @concelho = 'Vila Real de Santo António';
EXEC InsertLocalizacao @concelho = 'Vila Velha de Ródão';
EXEC InsertLocalizacao @concelho = 'Vila Verde';
EXEC InsertLocalizacao @concelho = 'Vila Viçosa';
EXEC InsertLocalizacao @concelho = 'Vimioso';
EXEC InsertLocalizacao @concelho = 'Vinhais';
EXEC InsertLocalizacao @concelho = 'Viseu';
EXEC InsertLocalizacao @concelho = 'Vizela';
EXEC InsertLocalizacao @concelho = 'Vouzela';

-- Insert USER
EXEC InsertUser @primeiroNome = 'João', @apelido = 'Silva', @email = 'joao.silva@example.com',
	@morada = 'Rua das Flores, 123', @codigoPostal = '1234-567', @idConcelho = 1,
	@dataNascimento = '1990-05-15', @telefone = '912345678', @subscricao = 1;
EXEC InsertUser @primeiroNome = 'Maria', @apelido = 'Santos', @email = 'maria.santos@example.com',
	@morada = 'Avenida das Palmeiras, 456', @codigoPostal = '9876-543', @idConcelho = 2,
	@dataNascimento = '1995-10-20', @telefone = '987654321', @subscricao = 0;

-- Insert LOGIN
EXEC InsertLogin @idUser = 1, @password = '12345678', @email = 'joao.silva@example.com';
EXEC InsertLogin @idUser = 2, @password = 'senha123', @email = 'maria.santos@example.com';

-- Insert LISTACOMPRAS
EXEC InsertListaCompras @idUser = 1, @descricao = 'Compras do mês';
EXEC InsertListaCompras @idUser = 2, @descricao = 'Itens de limpeza';

-- Insert LOJA
EXEC InsertLoja @descricao = 'Continente Bom Dia Braga', @idConcelho = 49, @morada = 'Rua Nova de Santa Cruz, 242', @latitude = '41.558341', @longitude = '-8.405852';
EXEC InsertLoja @descricao = 'Pingo Doce São Vicente', @idConcelho = 49, @morada = 'Rua de São Vicente, 79', @latitude = '41.549635', @longitude = '-8.426148';
EXEC InsertLoja @descricao = 'Lidl Braga Este', @idConcelho = 49, @morada = 'Avenida General Norton de Matos, 599', @latitude = '41.550165', @longitude = '-8.408975';
EXEC InsertLoja @descricao = 'Minipreço Maximinos', @idConcelho = 49, @morada = 'Rua dos Lameirões, 18', @latitude = '41.551933', @longitude = '-8.415474';

-- Insert CATEGORIA
EXEC InsertCategoria @descricao = 'Bebidas';
EXEC InsertCategoria @descricao = 'Carnes e Peixes';
EXEC InsertCategoria @descricao = 'Frutas e Vegetais';
EXEC InsertCategoria @descricao = 'Padaria e Pastelaria';
EXEC InsertCategoria @descricao = 'Laticínios';
EXEC InsertCategoria @descricao = 'Higiene Pessoal';
EXEC InsertCategoria @descricao = 'Limpeza Doméstica';

-- Insert SUBCATEGORIA
EXEC InsertSubCategoria @idCategoria = 1, @descricao = 'Águas';
EXEC InsertSubCategoria @idCategoria = 1, @descricao = 'Sumos e Refrigerantes';
EXEC InsertSubCategoria @idCategoria = 1, @descricao = 'Cervejas';
EXEC InsertSubCategoria @idCategoria = 1, @descricao = 'Vinhos';
EXEC InsertSubCategoria @idCategoria = 1, @descricao = 'Espirituosas';
EXEC InsertSubCategoria @idCategoria = 1, @descricao = 'Chás e Infusões';
EXEC InsertSubCategoria @idCategoria = 2, @descricao = 'Carnes Vermelhas';
EXEC InsertSubCategoria @idCategoria = 2, @descricao = 'Carnes Brancas';
EXEC InsertSubCategoria @idCategoria = 2, @descricao = 'Peixes Frescos';
EXEC InsertSubCategoria @idCategoria = 2, @descricao = 'Mariscos';
EXEC InsertSubCategoria @idCategoria = 2, @descricao = 'Enlatados de Peixe';
EXEC InsertSubCategoria @idCategoria = 2, @descricao = 'Charcutaria';
EXEC InsertSubCategoria @idCategoria = 2, @descricao = 'Bacalhau';
EXEC InsertSubCategoria @idCategoria = 2, @descricao = 'Congelados de Peixe';
EXEC InsertSubCategoria @idCategoria = 3, @descricao = 'Melancias e Melões';
EXEC InsertSubCategoria @idCategoria = 3, @descricao = 'Folhosas';
EXEC InsertSubCategoria @idCategoria = 3, @descricao = 'Cítricos';
EXEC InsertSubCategoria @idCategoria = 3, @descricao = 'Raízes';
EXEC InsertSubCategoria @idCategoria = 3, @descricao = 'Mistura para Salada';
EXEC InsertSubCategoria @idCategoria = 3, @descricao = 'Melancias e Melões';
EXEC InsertSubCategoria @idCategoria = 3, @descricao = 'Folhosas';
EXEC InsertSubCategoria @idCategoria = 3, @descricao = 'Cítricos';
EXEC InsertSubCategoria @idCategoria = 3, @descricao = 'Raízes';
EXEC InsertSubCategoria @idCategoria = 3, @descricao = 'Mistura para Salada';
EXEC InsertSubCategoria @idCategoria = 3, @descricao = 'Frutas Frescas';
EXEC InsertSubCategoria @idCategoria = 3, @descricao = 'Legumes';
EXEC InsertSubCategoria @idCategoria = 3, @descricao = 'Frutas Secas';
EXEC InsertSubCategoria @idCategoria = 3, @descricao = 'Hortaliças';
EXEC InsertSubCategoria @idCategoria = 3, @descricao = 'Saladas Prontas';
EXEC InsertSubCategoria @idCategoria = 4, @descricao = 'Pães';
EXEC InsertSubCategoria @idCategoria = 4, @descricao = 'Bolos';
EXEC InsertSubCategoria @idCategoria = 4, @descricao = 'Pastéis';
EXEC InsertSubCategoria @idCategoria = 4, @descricao = 'Croissants';
EXEC InsertSubCategoria @idCategoria = 4, @descricao = 'Biscoitos';
EXEC InsertSubCategoria @idCategoria = 4, @descricao = 'Tortas';
EXEC InsertSubCategoria @idCategoria = 5, @descricao = 'Leite';
EXEC InsertSubCategoria @idCategoria = 5, @descricao = 'Queijo';
EXEC InsertSubCategoria @idCategoria = 5, @descricao = 'Iogurte';
EXEC InsertSubCategoria @idCategoria = 5, @descricao = 'Manteiga';
EXEC InsertSubCategoria @idCategoria = 5, @descricao = 'Natas';
EXEC InsertSubCategoria @idCategoria = 5, @descricao = 'Requeijão';
EXEC InsertSubCategoria @idCategoria = 6, @descricao = 'Higiene Oral';
EXEC InsertSubCategoria @idCategoria = 6, @descricao = 'Cuidados com a Pele';
EXEC InsertSubCategoria @idCategoria = 6, @descricao = 'Cabelos e Couro Cabeludo';
EXEC InsertSubCategoria @idCategoria = 6, @descricao = 'Higiene Íntima';
EXEC InsertSubCategoria @idCategoria = 6, @descricao = 'Desodorantes e Antitranspirantes';
EXEC InsertSubCategoria @idCategoria = 6, @descricao = 'Perfumes e Colônias';
EXEC InsertSubCategoria @idCategoria = 7, @descricao = 'Detergentes para roupa';
EXEC InsertSubCategoria @idCategoria = 7, @descricao = 'Limpeza de superfícies';
EXEC InsertSubCategoria @idCategoria = 7, @descricao = 'Produtos de higiene e desinfetantes';
EXEC InsertSubCategoria @idCategoria = 7, @descricao = 'Utensílios de limpeza';
EXEC InsertSubCategoria @idCategoria = 7, @descricao = 'Acessórios para limpeza';
EXEC InsertSubCategoria @idCategoria = 7, @descricao = 'Produtos de limpeza especializados';
EXEC InsertSubCategoria @idCategoria = 7, @descricao = 'Cuidados com o chão';

-- Insert DESCRICAOUNIDADE
EXEC InsertDescricaoUnidade @descricao = 'kgs';
EXEC InsertDescricaoUnidade @descricao = 'lts';
EXEC InsertDescricaoUnidade @descricao = 'uni';

-- Insert MARCA
EXEC InsertMarca @descricao = 'Coca-Cola';
EXEC InsertMarca @descricao = 'Pepsi';
EXEC InsertMarca @descricao = 'Fanta';
EXEC InsertMarca @descricao = 'Sprite';
EXEC InsertMarca @descricao = 'Guaraná Antarctica';
EXEC InsertMarca @descricao = 'Sumol';
EXEC InsertMarca @descricao = 'Nestea';
EXEC InsertMarca @descricao = 'Schweppes';
EXEC InsertMarca @descricao = 'Serra da Estrela';
EXEC InsertMarca @descricao = 'Luso';
EXEC InsertMarca @descricao = 'Castello';
EXEC InsertMarca @descricao = 'Caldas de Penacova';
EXEC InsertMarca @descricao = 'Pedras Salgadas';
EXEC InsertMarca @descricao = 'Vidago';
EXEC InsertMarca @descricao = 'Montanha';
EXEC InsertMarca @descricao = 'Fonte Viva';
EXEC InsertMarca @descricao = 'Carvalhelhos';
EXEC InsertMarca @descricao = 'Vimeiro';
EXEC InsertMarca @descricao = 'Super Bock';
EXEC InsertMarca @descricao = 'Sagres';
EXEC InsertMarca @descricao = 'Sommersby';
EXEC InsertMarca @descricao = 'Sangria Lolea';
EXEC InsertMarca @descricao = 'Campofrío';
EXEC InsertMarca @descricao = 'Nacional';
EXEC InsertMarca @descricao = 'Pescanova';
EXEC InsertMarca @descricao = 'Ibercarnes';
EXEC InsertMarca @descricao = 'Salmão do Mar';
EXEC InsertMarca @descricao = 'Riberalves';
EXEC InsertMarca @descricao = 'Nobre';
EXEC InsertMarca @descricao = 'Açorda';
EXEC InsertMarca @descricao = 'Marca Branca';
EXEC InsertMarca @descricao = 'Bimbo';
EXEC InsertMarca @descricao = 'Continental';
EXEC InsertMarca @descricao = 'Puratos';
EXEC InsertMarca @descricao = 'Pingo Doce';
EXEC InsertMarca @descricao = 'Panrico';
EXEC InsertMarca @descricao = 'Espiga';
EXEC InsertMarca @descricao = 'Harina';
EXEC InsertMarca @descricao = 'Lusitana';
EXEC InsertMarca @descricao = 'Nestlé';
EXEC InsertMarca @descricao = 'Danone';
EXEC InsertMarca @descricao = 'Parmalat';
EXEC InsertMarca @descricao = 'Mimosa';
EXEC InsertMarca @descricao = 'Pingo Doce';
EXEC InsertMarca @descricao = 'Lactogal';
EXEC InsertMarca @descricao = 'Queijos Santiago';
EXEC InsertMarca @descricao = 'Vigor';
EXEC InsertMarca @descricao = 'Primor';
EXEC InsertMarca @descricao = 'Dove';
EXEC InsertMarca @descricao = 'Nivea';
EXEC InsertMarca @descricao = 'Pantene';
EXEC InsertMarca @descricao = 'Colgate';
EXEC InsertMarca @descricao = 'Head & Shoulders';
EXEC InsertMarca @descricao = 'Garnier';
EXEC InsertMarca @descricao = 'Johnson & Johnson';
EXEC InsertMarca @descricao = 'Oral-B';
EXEC InsertMarca @descricao = 'Neutrogena';
EXEC InsertMarca @descricao = 'Gillette';
EXEC InsertMarca @descricao = 'Skip';
EXEC InsertMarca @descricao = 'Cif';
EXEC InsertMarca @descricao = 'Fairy';
EXEC InsertMarca @descricao = 'Ariel';
EXEC InsertMarca @descricao = 'Mr. Proper';
EXEC InsertMarca @descricao = 'Neoblanc';
EXEC InsertMarca @descricao = 'Sonasol';
EXEC InsertMarca @descricao = 'Vanish';
EXEC InsertMarca @descricao = 'Oral-B';

-- Insert PRODUTO
 
EXEC InsertProduto @nomeProduto = 'Coca-Cola', @descricao = 'Refrigerante de cola', @idSubCategoria = 2, @idMarca = 1, @unidade = 1, @idDescricaoUnidade = 3, @isVegetarian = 1, @isVegan = 1, @isGlutenFree = 1;
EXEC InsertProduto @nomeProduto = 'Super Bock', @descricao = 'Cerveja', @idSubCategoria = 3, @idMarca = 19, @unidade = 0.33, @idDescricaoUnidade = 2, @isVegetarian = 1, @isVegan = 1, @isGlutenFree = 0;
EXEC InsertProduto @nomeProduto = 'Vinho Tinto', @descricao = 'Vinho tinto', @idSubCategoria = 4, @idMarca = 14, @unidade = 0.75, @idDescricaoUnidade = 2, @isVegetarian = 1, @isVegan = 1, @isGlutenFree = 1;
EXEC InsertProduto @nomeProduto = 'Johnnie Walker', @descricao = 'Whisky escocês', @idSubCategoria = 5, @idMarca = 5, @unidade = 0.7, @idDescricaoUnidade = 2, @isVegetarian = 1, @isVegan = 1, @isGlutenFree = 1;
EXEC InsertProduto @nomeProduto = 'Chá Verde', @descricao = 'Chá verde', @idSubCategoria = 6, @idMarca = 7, @unidade = 25, @idDescricaoUnidade = 3, @isVegetarian = 1, @isVegan = 1, @isGlutenFree = 1;
EXEC InsertProduto @nomeProduto = 'Vaca para Grelhar', @descricao = 'Carne de vaca para grelhar', @idSubCategoria = 7, @idMarca = 26, @unidade = 0.2, @idDescricaoUnidade = 1, @isVegetarian = 0, @isVegan = 0, @isGlutenFree = 1;
EXEC InsertProduto @nomeProduto = 'Peito de Frango', @descricao = 'Peito de frango fresco', @idSubCategoria = 8, @idMarca = 29, @unidade = 0.3, @idDescricaoUnidade = 1, @isVegetarian = 0, @isVegan = 0, @isGlutenFree = 1;
EXEC InsertProduto @nomeProduto = 'Salmão Fresco', @descricao = 'Salmão fresco', @idSubCategoria = 9, @idMarca = 25, @unidade = 0.5, @idDescricaoUnidade = 1, @isVegetarian = 0, @isVegan = 0, @isGlutenFree = 1;
EXEC InsertProduto @nomeProduto = 'Camarão Congelado', @descricao = 'Camarão congelado', @idSubCategoria = 10, @idMarca = 24, @unidade = 0.5, @idDescricaoUnidade = 1, @isVegetarian = 0, @isVegan = 0, @isGlutenFree = 1;

-- Insert LINHALISTACOMPRAS
EXEC InsertLinhaListaCompras @idListaCompras = 1, @idProduto = 1, @quantidade = 2.5;
EXEC InsertLinhaListaCompras @idListaCompras = 1, @idProduto = 2, @quantidade = 3;
EXEC InsertLinhaListaCompras @idListaCompras = 1, @idProduto = 3, @quantidade = 6;
EXEC InsertLinhaListaCompras @idListaCompras = 1, @idProduto = 4, @quantidade = 1;
EXEC InsertLinhaListaCompras @idListaCompras = 1, @idProduto = 5, @quantidade = 0.7;
EXEC InsertLinhaListaCompras @idListaCompras = 1, @idProduto = 6, @quantidade = 1;
EXEC InsertLinhaListaCompras @idListaCompras = 1, @idProduto = 7, @quantidade = 0.4;
EXEC InsertLinhaListaCompras @idListaCompras = 1, @idProduto = 8, @quantidade = 0.5;
EXEC InsertLinhaListaCompras @idListaCompras = 1, @idProduto = 9, @quantidade = 0.3;
EXEC InsertLinhaListaCompras @idListaCompras = 1, @idProduto = 10, @quantidade = 0.6;

EXEC InsertLinhaListaCompras @idListaCompras = 2, @idProduto = 1, @quantidade = 3;
EXEC InsertLinhaListaCompras @idListaCompras = 2, @idProduto = 2, @quantidade = 2;
EXEC InsertLinhaListaCompras @idListaCompras = 2, @idProduto = 3, @quantidade = 4;
EXEC InsertLinhaListaCompras @idListaCompras = 2, @idProduto = 4, @quantidade = 2;
EXEC InsertLinhaListaCompras @idListaCompras = 2, @idProduto = 5, @quantidade = 1;
EXEC InsertLinhaListaCompras @idListaCompras = 2, @idProduto = 6, @quantidade = 1;
EXEC InsertLinhaListaCompras @idListaCompras = 2, @idProduto = 7, @quantidade = 0.5;
EXEC InsertLinhaListaCompras @idListaCompras = 2, @idProduto = 8, @quantidade = 0.4;
EXEC InsertLinhaListaCompras @idListaCompras = 2, @idProduto = 9, @quantidade = 0.6;
EXEC InsertLinhaListaCompras @idListaCompras = 2, @idProduto = 10, @quantidade = 0.8;

-- Insert LOJAPRODUTO
EXEC InsertLojaProduto @idProduto = 1, @idLoja = 1, @preco = 1.99;
EXEC InsertLojaProduto @idProduto = 1, @idLoja = 2, @preco = 2.29;
EXEC InsertLojaProduto @idProduto = 1, @idLoja = 3, @preco = 1.79;
EXEC InsertLojaProduto @idProduto = 1, @idLoja = 4, @preco = 2.49;

EXEC InsertLojaProduto @idProduto = 2, @idLoja = 1, @preco = 1.49;
EXEC InsertLojaProduto @idProduto = 2, @idLoja = 2, @preco = 1.79;
EXEC InsertLojaProduto @idProduto = 2, @idLoja = 3, @preco = 1.39;
EXEC InsertLojaProduto @idProduto = 2, @idLoja = 4, @preco = 1.99;

EXEC InsertLojaProduto @idProduto = 3, @idLoja = 1, @preco = 0.99;
EXEC InsertLojaProduto @idProduto = 3, @idLoja = 2, @preco = 1.29;
EXEC InsertLojaProduto @idProduto = 3, @idLoja = 3, @preco = 0.89;
EXEC InsertLojaProduto @idProduto = 3, @idLoja = 4, @preco = 1.49;

EXEC InsertLojaProduto @idProduto = 4, @idLoja = 1, @preco = 4.99;
EXEC InsertLojaProduto @idProduto = 4, @idLoja = 2, @preco = 5.49;
EXEC InsertLojaProduto @idProduto = 4, @idLoja = 3, @preco = 4.79;

-- Insert LISTAFAVORITOS
EXEC InsertListaFavoritos @idUser = 1, @idProduto = 1;
EXEC InsertListaFavoritos @idUser = 1, @idProduto = 2;
EXEC InsertListaFavoritos @idUser = 1, @idProduto = 3;
EXEC InsertListaFavoritos @idUser = 2, @idProduto = 4;
EXEC InsertListaFavoritos @idUser = 2, @idProduto = 5;